// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package internal

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson62181af4DecodeFruitingJobParserInternal(in *jlexer.Lexer, out *ParseByPositionTask) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "parser":
			out.Parser = Parser(in.String())
		case "chat_id":
			out.ChatId = int64(in.Int64())
		case "position_name":
			out.PositionName = Name(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson62181af4EncodeFruitingJobParserInternal(out *jwriter.Writer, in ParseByPositionTask) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"parser\":"
		out.RawString(prefix[1:])
		out.String(string(in.Parser))
	}
	{
		const prefix string = ",\"chat_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ChatId))
	}
	{
		const prefix string = ",\"position_name\":"
		out.RawString(prefix)
		out.String(string(in.PositionName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ParseByPositionTask) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson62181af4EncodeFruitingJobParserInternal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ParseByPositionTask) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson62181af4EncodeFruitingJobParserInternal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ParseByPositionTask) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson62181af4DecodeFruitingJobParserInternal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ParseByPositionTask) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson62181af4DecodeFruitingJobParserInternal(l, v)
}
